name: EarthSMP
version: '${version}'
main: dev.talwat.earthsmp.Earthsmp
api-version: 1.19
authors: [ talwat ]
description: Talwat's EarthSMP plugin
depend:
  - squaremap
commands:
  earth:
    description: Custom EarthSMP commands
    usage: /earth help