name: Gradle Build

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: |
        ./gradlew build
        rm -rf ./build/libs/*-all.jar

    - name: Upload assets to release
      if: github.event_name == 'release'
      shell: bash
      run: |
        gh release upload ${{github.event.release.tag_name}} ./build/libs/earthsmp-*.jar

    - name: Upload build artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: ./build/libs/earthsmp-*.jar
